name: called
on:
  workflow_call:
  workflow_dispatch:

jobs:
  called-job-1:
    runs-on: ubuntu-latest
    steps:
     - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
